export interface PropertyData {
  id: string;
  image: string;
  topBadge?: string;
  name: string;
  location: string;
  locationDetail: string;
  stars: number;
  tagLabels: string[];
  note: string;
  noteColor: string;
  ratingScore: string;
  ratingScoreNum: number;
  ratingLabel: string;
  ratingCount: string;
  oldPrice?: string;
  price: string;
  priceNum: number;
  propertyType: "Hotels" | "Resorts" | "Apartments" | "Villas";
  neighborhood: "Patong" | "Karon" | "Kata" | "Kamala";
  bedType: "Single" | "Double" | "King";
}

export const ALL_PROPERTIES: PropertyData[] = [
  {
    id: "1",
    image: "/The Azure Serenity Resort.png",
    topBadge: "Top Choice",
    name: "The Azure Serenity Resort",
    location: "Ubud, Bali",
    locationDetail: "2.5 km from center",
    stars: 5,
    tagLabels: ["Free Wi-Fi", "Pool", "Breakfast"],
    note: "Only 2 rooms left at this price!",
    noteColor: "#B61B4A",
    ratingScore: "8.9",
    ratingScoreNum: 8.9,
    ratingLabel: "Excellent",
    ratingCount: "1,240",
    oldPrice: "$320",
    price: "$284",
    priceNum: 284,
    propertyType: "Resorts",
    neighborhood: "Kata",
    bedType: "King",
  },
  {
    id: "2",
    image: "/Lumina Beach Villas.png",
    name: "Lumina Beach Villas",
    location: "Seminyak, Bali",
    locationDetail: "Beachfront",
    stars: 4,
    tagLabels: ["Private Beach", "Spa"],
    note: "Free cancellation before Oct 10",
    noteColor: "#16A34A",
    ratingScore: "9.2",
    ratingScoreNum: 9.2,
    ratingLabel: "Exceptional",
    ratingCount: "856",
    price: "$415",
    priceNum: 415,
    propertyType: "Villas",
    neighborhood: "Karon",
    bedType: "Double",
  },
  {
    id: "3",
    image: "/The Palms Sanctuary.png",
    name: "The Palms Sanctuary",
    location: "Nusa Dua, Bali",
    locationDetail: "0.8 km from beach",
    stars: 4,
    tagLabels: ["Airport Shuttle", "Gym"],
    note: "Breakfast + Dinner deal available",
    noteColor: "#D97706",
    ratingScore: "8.4",
    ratingScoreNum: 8.4,
    ratingLabel: "Great",
    ratingCount: "2,102",
    price: "$189",
    priceNum: 189,
    propertyType: "Resorts",
    neighborhood: "Patong",
    bedType: "King",
  },
  {
    id: "4",
    image: "/Kuta bay hotel.png",
    name: "Kuta Bay Hotel",
    location: "Kuta, Bali",
    locationDetail: "500m from beach",
    stars: 3,
    tagLabels: ["Free Wi-Fi", "Parking"],
    note: "Popular with budget travelers",
    noteColor: "#D97706",
    ratingScore: "7.5",
    ratingScoreNum: 7.5,
    ratingLabel: "Good",
    ratingCount: "3,412",
    price: "$89",
    priceNum: 89,
    propertyType: "Hotels",
    neighborhood: "Patong",
    bedType: "Double",
  },
  {
    id: "5",
    image: "/Seminyak beach club resort.png",
    name: "Seminyak Garden Suites",
    location: "Seminyak, Bali",
    locationDetail: "Central Seminyak",
    stars: 4,
    tagLabels: ["Free Wi-Fi", "Fitness Center"],
    note: "Free cancellation before Nov 1",
    noteColor: "#16A34A",
    ratingScore: "8.1",
    ratingScoreNum: 8.1,
    ratingLabel: "Very Good",
    ratingCount: "678",
    price: "$156",
    priceNum: 156,
    propertyType: "Apartments",
    neighborhood: "Kamala",
    bedType: "Single",
  },
  {
    id: "6",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=512&h=400&fit=crop&q=80",
    name: "Ubud Forest Retreat",
    location: "Ubud, Bali",
    locationDetail: "Deep jungle setting",
    stars: 5,
    tagLabels: ["Free Wi-Fi", "Pool", "Spa"],
    note: "Voted #1 Eco Resort 2024",
    noteColor: "#16A34A",
    ratingScore: "9.0",
    ratingScoreNum: 9.0,
    ratingLabel: "Superb",
    ratingCount: "934",
    oldPrice: "$380",
    price: "$320",
    priceNum: 320,
    propertyType: "Resorts",
    neighborhood: "Kata",
    bedType: "King",
  },
  {
    id: "7",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=512&h=400&fit=crop&q=80",
    topBadge: "Top Choice",
    name: "Jimbaran Cliff Villa",
    location: "Jimbaran, Bali",
    locationDetail: "Clifftop ocean views",
    stars: 5,
    tagLabels: ["Private Beach", "Pool", "Spa"],
    note: "Last 1 villa at this price!",
    noteColor: "#B61B4A",
    ratingScore: "9.5",
    ratingScoreNum: 9.5,
    ratingLabel: "Exceptional",
    ratingCount: "412",
    oldPrice: "$750",
    price: "$580",
    priceNum: 580,
    propertyType: "Villas",
    neighborhood: "Karon",
    bedType: "King",
  },
  {
    id: "8",
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=512&h=400&fit=crop&q=80",
    name: "Nusa Dua Beach Hotel",
    location: "Nusa Dua, Bali",
    locationDetail: "On the beach",
    stars: 4,
    tagLabels: ["Free Wi-Fi", "Pool", "Airport Shuttle"],
    note: "Complimentary airport pickup",
    noteColor: "#16A34A",
    ratingScore: "8.3",
    ratingScoreNum: 8.3,
    ratingLabel: "Great",
    ratingCount: "1,890",
    price: "$210",
    priceNum: 210,
    propertyType: "Hotels",
    neighborhood: "Kamala",
    bedType: "Double",
  },
  {
    id: "9",
    image: "https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=512&h=400&fit=crop&q=80",
    name: "Canggu Surf Lodge",
    location: "Canggu, Bali",
    locationDetail: "Steps to Echo Beach",
    stars: 3,
    tagLabels: ["Free Wi-Fi", "Parking"],
    note: "Great surf break nearby",
    noteColor: "#D97706",
    ratingScore: "7.8",
    ratingScoreNum: 7.8,
    ratingLabel: "Good",
    ratingCount: "1,045",
    price: "$75",
    priceNum: 75,
    propertyType: "Hotels",
    neighborhood: "Patong",
    bedType: "Single",
  },
  {
    id: "10",
    image: "https://images.unsplash.com/photo-1573843981267-be1480760ef7?w=512&h=400&fit=crop&q=80",
    name: "Uluwatu Sky Resort",
    location: "Uluwatu, Bali",
    locationDetail: "Clifftop infinity pool",
    stars: 5,
    tagLabels: ["Pool", "Spa", "Breakfast"],
    note: "Sunset views included",
    noteColor: "#16A34A",
    ratingScore: "9.1",
    ratingScoreNum: 9.1,
    ratingLabel: "Exceptional",
    ratingCount: "567",
    oldPrice: "$520",
    price: "$450",
    priceNum: 450,
    propertyType: "Resorts",
    neighborhood: "Kata",
    bedType: "King",
  },
  {
    id: "11",
    image: "https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?w=512&h=400&fit=crop&q=80",
    name: "Kerobokan Garden Apartments",
    location: "Kerobokan, Bali",
    locationDetail: "Quiet neighborhood",
    stars: 3,
    tagLabels: ["Free Wi-Fi", "Parking"],
    note: "Monthly rates available",
    noteColor: "#D97706",
    ratingScore: "7.2",
    ratingScoreNum: 7.2,
    ratingLabel: "Good",
    ratingCount: "289",
    price: "$65",
    priceNum: 65,
    propertyType: "Apartments",
    neighborhood: "Karon",
    bedType: "Single",
  },
  {
    id: "12",
    image: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?w=512&h=400&fit=crop&q=80",
    name: "Sanur Beachside Villas",
    location: "Sanur, Bali",
    locationDetail: "Calm beachfront",
    stars: 4,
    tagLabels: ["Private Beach", "Free Wi-Fi"],
    note: "Family-friendly environment",
    noteColor: "#16A34A",
    ratingScore: "8.6",
    ratingScoreNum: 8.6,
    ratingLabel: "Excellent",
    ratingCount: "723",
    price: "$265",
    priceNum: 265,
    propertyType: "Villas",
    neighborhood: "Kamala",
    bedType: "Double",
  },
];

export const ITEMS_PER_PAGE = 3;

export const DESTINATIONS = [
  "Bali, Indonesia",
  "Phuket, Thailand",
  "Kyoto, Japan",
  "Seoul, South Korea",
];

export const DATE_RANGES = [
  "Oct 12 - Oct 19, 2024",
  "Oct 19 - Oct 26, 2024",
  "Nov 1 - Nov 8, 2024",
  "Nov 15 - Nov 22, 2024",
];

export const SORT_OPTIONS = [
  "Recommended",
  "Price: Low to High",
  "Price: High to Low",
  "Review Score",
  "Star Rating",
];

export const FACILITY_FILTER_MAP: Record<string, string[]> = {
  "Free Wi-Fi": ["Free Wi-Fi"],
  "Swimming Pool": ["Pool"],
  "Fitness Center": ["Fitness Center", "Gym"],
  "Spa": ["Spa"],
  "Parking": ["Parking"],
  "Pet Friendly": ["Pet Friendly"],
};
